/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Autocomplete: typeof import('./src/components/app/Autocomplete.vue')['default']
    Avatar: typeof import('./src/components/app/dashboard/profile/Avatar.vue')['default']
    Bar: typeof import('./src/components/dashboard/bar/Bar.vue')['default']
    BarSimple: typeof import('./src/components/app/dashboard/widgets/BarSimple.vue')['default']
    Compose: typeof import('./src/components/app/dashboard/users/Compose.vue')['default']
    DataTable: typeof import('./src/components/app/DataTable.vue')['default']
    DatePicker: typeof import('./src/components/app/DatePicker.vue')['default']
    Default: typeof import('./src/components/app/dashboard/bar/notifications/templates/Default.vue')['default']
    DeleteBtn: typeof import('./src/components/app/dashboard/DeleteBtn.vue')['default']
    Dialog: typeof import('./src/components/app/Dialog.vue')['default']
    EditBtn: typeof import('./src/components/app/dashboard/EditBtn.vue')['default']
    EmojiesPicker: typeof import('./src/components/app/dashboard/chat/sender/EmojiesPicker.vue')['default']
    Empty: typeof import('./src/components/app/dashboard/chat/Empty.vue')['default']
    Filter: typeof import('./src/components/users/Filter.vue')['default']
    FilterTable: typeof import('./src/components/app/FilterTable.vue')['default']
    FriendRequest: typeof import('./src/components/app/dashboard/bar/notifications/templates/FriendRequest.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Item: typeof import('./src/components/dashboard/drawer/Item.vue')['default']
    ItemGroup: typeof import('./src/components/dashboard/drawer/ItemGroup.vue')['default']
    LanguageMenu: typeof import('./src/components/dashboard/bar/LanguageMenu.vue')['default']
    List: typeof import('./src/components/app/List.vue')['default']
    Loader: typeof import('./src/components/dashboard/Loader.vue')['default']
    Menu: typeof import('./src/components/app/dashboard/bar/notifications/Menu.vue')['default']
    NavigationDrawer: typeof import('./src/components/dashboard/drawer/NavigationDrawer.vue')['default']
    Pie: typeof import('./src/components/app/dashboard/widgets/Pie.vue')['default']
    Recorder: typeof import('./src/components/app/dashboard/chat/sender/Recorder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesRevenue: typeof import('./src/components/app/dashboard/widgets/SalesRevenue.vue')['default']
    Select: typeof import('./src/components/app/Select.vue')['default']
    Sender: typeof import('./src/components/app/dashboard/chat/sender/Sender.vue')['default']
    Settings: typeof import('./src/components/app/dashboard/chat/Settings.vue')['default']
    SettingsMenu: typeof import('./src/components/dashboard/bar/SettingsMenu.vue')['default']
    Sheet: typeof import('./src/components/app/Sheet.vue')['default']
    Snackbar: typeof import('./src/components/app/Snackbar.vue')['default']
    Stat: typeof import('./src/components/app/dashboard/widgets/Stat.vue')['default']
    Text: typeof import('./src/components/app/dashboard/chat/messages/Text.vue')['default']
    TextField: typeof import('./src/components/app/TextField.vue')['default']
    ThemeToggle: typeof import('./src/components/app/ThemeToggle.vue')['default']
    Toolbar: typeof import('./src/components/app/dashboard/chat/Toolbar.vue')['default']
    TooltipBtn: typeof import('./src/components/app/TooltipBtn.vue')['default']
    Typing: typeof import('./src/components/app/dashboard/chat/Typing.vue')['default']
    Uploader: typeof import('./src/components/app/Uploader.vue')['default']
    Voice: typeof import('./src/components/app/dashboard/chat/messages/Voice.vue')['default']
    WebsitePerformance: typeof import('./src/components/app/dashboard/widgets/WebsitePerformance.vue')['default']
  }
}
